### ISSUE TITLE
Integrate JSON parser in main

### ISSUE THREAD

**Issue by Naxaes** [Naxaes/CI-server#16]
Use the JSON parser to parse the incoming message from Github and send the appropriate response.

**Comment by Naxaes** [comment]
On it!

**Comment by Naxaes** [comment]
This is a comment to trigger an event to CI-server.

**Comment by Naxaes** [comment]
Have to try again...

**Comment by Naxaes** [comment]
COMMENT!

**Comment by ghodt** [comment]
Is this fixed now?
